# Generated by Django 5.2.4 on 2025-07-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('massage', models.TextField()),
                ('enqdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
