# Generated by Django 5.2.4 on 2025-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='massage',
            new_name='message',
        ),
    ]
