# Generated by Django 5.2.4 on 2025-08-01 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_logininfo_rename_massage_enquiry_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contactno', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.logininfo')),
            ],
        ),
    ]
