# Generated by Django 5.2.4 on 2025-08-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
