# Generated by Django 5.2.4 on 2025-09-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_book_original_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
