# Generated by Django 5.2.4 on 2025-08-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_bookcategory_bookitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookItem',
        ),
    ]
